title: Lmyslinki's Tech Blog
author: Łukasz Myśliński
email: I'll need need some new address for this
description: A place where I write about coding and all kinds of stuff
# social links
twitter_username: lmyslinski # DO NOT include the @ character, or else the build will fail!
github_username:  lmyslinski # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: lanyon
